apiVersion: apps/v1
kind: Deployment
metadata:
  name: browse-library-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: browse-library
  template:
    metadata:
      labels:
        app: browse-library
    spec:
      containers:
        - name: browse-library
          image: markloboda/browse_library_service:latest
          imagePullPolicy: Always
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: omdb
                  key: api-key
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /service/browse-library/health/live
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: browse-library
spec:
  type: ClusterIP
  selector:
    app: browse-library
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
