apiVersion: apps/v1
kind: Deployment
metadata:
  name: browse-library-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: browse-library
  template:
    metadata:
      labels:
        app: browse-library
    spec:
      containers:
      - name: browse-library
        image: markloboda/browse_library_service:latest
        imagePullPolicy: Always
        env:
        - name: FLASK_ENV
          value: development
        - name: FLASK_DEBUG
          value: "1"
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: omdb
              key: api-key
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: browse-library
spec:
  type: ClusterIP
  selector:
    app: browse-library
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080