apiVersion: batch/v1
kind: Job
metadata:
  name: set-flask-debug-true
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      containers:
        - name: set-flask-debug-true
          image: bitnami/etcd:3.4.13
          command: ["/bin/sh", "-c"]
          args:
            - |
              ETCDCTL_API=3 etcdctl --endpoints=http://etcd:2379 put /config/FLASK_DEBUG "${FLASK_DEBUG_VALUE}"
          env:
            - name: FLASK_DEBUG_VALUE
              value: "1"
      restartPolicy: Never
