apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-library-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-library-frontend
  template:
    metadata:
      labels:
        app: movie-library-frontend
    spec:
      containers:
      - name: movie-library-frontend
        image: markloboda/movie_library_frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: movie-library-frontend
spec:
  selector:
    app: movie-library-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP