apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-interface-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-interface
  template:
    metadata:
      labels:
        app: user-interface
    spec:
      containers:
        - name: user-interface
          image: markloboda/user-interface:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: user-interface
spec:
  selector:
    app: user-interface
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
