apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchlist-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watchlist
  template:
    metadata:
      labels:
        app: watchlist
    spec:
      containers:
        - name: watchlist
          image: ${{ secrets.DOCKER_USERNAME }}/watchlist_service:latest
          imagePullPolicy: Always
          env:
            - name: DB_URI
              valueFrom:
                secretKeyRef:
                  name: database
                  key: uri
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /service/watchlist/health/live
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: watchlist
spec:
  type: ClusterIP
  selector:
    app: watchlist
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
