apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-register-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-register-service
  template:
    metadata:
      labels:
        app: login-register-service
    spec:
      containers:
      - name: login-register-service
        image: login-register-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: login-register-service
spec:
  selector:
    app: login-register-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer