name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for watchlist service
        uses: docker/build-push-action@v3
        with:
          file: src/watchlist_service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/watchlist_service:latest

      - name: Build and push Docker image for login register service
        uses: docker/build-push-action@v3
        with:
          file: src/login_register_service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/login_register_service:latest

      - name: Build and push Docker image for browse library service
        uses: docker/build-push-action@v3
        with:
          file: src/browse_library_service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/browse_library_service:latest

      - name: Build and push Docker image for user interface
        uses: docker/build-push-action@v3
        with:
          file: src/user_interface/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/user-interface:latest

      - name: Build and push Docker image for OpenAPI
        uses: docker/build-push-action@v3
        with:
          file: src/OpenAPI/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/openapi_service:latest
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Kubernetes
        uses: digitalocean/app_action/deploy@v2
        with:
          token: ${{ secrets.KUBE_TOKEN }}
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.9.5/deploy/static/provider/cloud/deploy.yaml
          kubectl apply -f "ingress.yaml"
          kubectl apply -f "etcd.yaml"
          kubectl apply -f "secret.yaml"
          kubectl apply -f "browse-library.yaml"
          kubectl apply -f "login-register.yaml"
          kubectl apply -f "user-interface.yaml"
          kubectl apply -f "watchlist.yaml"
          kubectl apply -f "openapi.yaml"
