name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for watchlist service
        uses: docker/build-push-action@v3
        with:
          file: src/watchlist_service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/watchlist_service:latest

      - name: Build and push Docker image for login register service
        uses: docker/build-push-action@v3
        with:
          file: src/login_register_service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/login_register_service:latest

      - name: Build and push Docker image for browse library service
        uses: docker/build-push-action@v3
        with:
          file: src/browse_library_service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/browse_library_service:latest

      - name: Build and push Docker image for user interface
        uses: docker/build-push-action@v3
        with:
          file: src/user_interface/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/user-interface:latest

      - name: Build and push Docker image for OpenAPI
        uses: docker/build-push-action@v3
        with:
          file: src/OpenAPI/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/openapi_service:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: "latest"

      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          ./k8s/deploy.ps1
